title: "Ultimate Guide to SLSA"
description: "Supply-chain Levels for Software Artifacts — a comprehensive technical reference."
remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme
url: "https://cjohannsen81.github.io"
baseurl: "/slsa-guide"
